# Generated by Django 3.2 on 2022-09-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seopagesubtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sub_title', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Header - SEO Page',
                'verbose_name_plural': 'Header - SEO Page',
            },
        ),
    ]
