# Generated by Django 3.2 on 2022-09-02 11:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmarketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seopagefirstsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='aboutus')),
            ],
            options={
                'verbose_name': 'First Section - Seo Page',
                'verbose_name_plural': 'First Section - Seo Page',
            },
        ),
    ]
