# Generated by Django 3.2 on 2022-09-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmarketing', '0002_seopagefirstsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seopagebenefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Benefits - Seo Page',
                'verbose_name_plural': 'Benefits - Seo Page',
            },
        ),
    ]
