# Generated by Django 3.2 on 2022-09-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmarketing', '0003_seopagebenefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='seopagebenefits',
            name='bd_coloer',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
