# Generated by Django 3.2 on 2022-09-02 15:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmarketing', '0004_seopagebenefits_bd_coloer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seoservicefaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Faq - Seo Page',
                'verbose_name_plural': 'Faq - Seo Page',
            },
        ),
    ]
