# Generated by Django 3.2 on 2022-09-02 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmarketing', '0006_productimage_seoportfolio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='PortfolioImage',
        ),
    ]
