# Generated by Django 3.2 on 2022-09-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmarketing', '0008_serviceselect'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioimage',
            name='img_alt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='seopagefirstsection',
            name='img_alt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='seoportfolio',
            name='img_alt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
