# Generated by Django 3.2 on 2022-09-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmarketing', '0009_auto_20220917_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seoservicehomepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=200)),
                ('meta_description', models.CharField(max_length=500)),
                ('meta_keywords', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'SEO Service - SEO Homepage',
                'verbose_name_plural': 'SEO Service - SEO Homepage',
            },
        ),
    ]
