# Generated by Django 3.2 on 2022-09-24 19:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmarketing', '0012_seoportfoliopagemeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seoservicehomepagecontentandmeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_site_title', models.CharField(max_length=200)),
                ('meta_description', models.CharField(max_length=500)),
                ('meta_keywords', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=200)),
                ('sub_title', models.CharField(max_length=500)),
                ('firstsection_title', models.CharField(max_length=500)),
                ('firstsection_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('firstsection_image', models.ImageField(upload_to='aboutus')),
                ('firstsection_img_alt', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'SEO Service Page Meta - SEO Homepage',
                'verbose_name_plural': 'SEO Service Page Meta - SEO Homepage',
            },
        ),
        migrations.DeleteModel(
            name='Seopagefirstsection',
        ),
        migrations.DeleteModel(
            name='Seopagesubtitle',
        ),
        migrations.DeleteModel(
            name='Seoservicehomepagemeta',
        ),
    ]
