# Generated by Django 3.2 on 2022-09-24 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmarketing', '0013_auto_20220925_0151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seoservicehomepagecontentandmeta',
            options={'verbose_name': 'SEO Service Page Content and Meta - SEO Homepage', 'verbose_name_plural': 'SEO Service Page Content and Meta - SEO Homepage'},
        ),
    ]
