# Generated by Django 3.2 on 2022-09-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmarketing', '0014_alter_seoservicehomepagecontentandmeta_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seoportfoliopagemeta',
        ),
        migrations.AddField(
            model_name='seoportfolio',
            name='meta_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seoportfolio',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seoportfolio',
            name='meta_site_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
