# Generated by Django 3.2 on 2022-08-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='header_homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=200)),
                ('sort_description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='header_homepage')),
            ],
            options={
                'verbose_name': 'Header Homepage',
                'verbose_name_plural': 'Header Homepage',
            },
        ),
    ]
