# Generated by Django 3.2 on 2022-08-28 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='header_homepage',
            new_name='Headerhomepage',
        ),
    ]
