# Generated by Django 3.2 on 2022-08-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_startupsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonialsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_speech', models.TextField()),
                ('image', models.ImageField(upload_to='testimonial_section')),
                ('name', models.CharField(max_length=100)),
                ('organigation', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Testimonial Section',
                'verbose_name_plural': 'Testimonial Section',
            },
        ),
    ]
