# Generated by Django 3.2 on 2022-08-29 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_testimonialsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactussection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+8801711111000'.", regex='^\\+?1?\\d{11,14}$')])),
            ],
            options={
                'verbose_name': 'Contact-us Section',
                'verbose_name_plural': 'Contact-us Section',
            },
        ),
    ]
