# Generated by Django 3.2 on 2022-08-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_contactussection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footersection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_main_description', models.TextField()),
                ('newsletter_description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Footer Section',
                'verbose_name_plural': 'Footer Section',
            },
        ),
    ]
