# Generated by Django 3.2 on 2022-09-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_footersection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutuspagesubtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'About Page Subtitle',
                'verbose_name_plural': 'About Page Subtitle',
            },
        ),
        migrations.AlterModelOptions(
            name='contactussection',
            options={'verbose_name': 'Contact-us Homepage', 'verbose_name_plural': 'Contact-us Homepage'},
        ),
        migrations.AlterModelOptions(
            name='footersection',
            options={'verbose_name': 'Footer Homepage', 'verbose_name_plural': 'Footer Homepage'},
        ),
        migrations.AlterModelOptions(
            name='startupsection',
            options={'verbose_name': 'Startup Homepage', 'verbose_name_plural': 'Startup Homepage'},
        ),
        migrations.AlterModelOptions(
            name='testimonialsection',
            options={'verbose_name': 'Testimonial Homepage', 'verbose_name_plural': 'Testimonial Homepage'},
        ),
    ]
