# Generated by Django 3.2 on 2022-09-02 09:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20220902_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutussecondsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='aboutus')),
            ],
            options={
                'verbose_name': 'Second Section - About Page',
                'verbose_name_plural': 'Second Section - About Page',
            },
        ),
    ]
