# Generated by Django 3.2 on 2022-09-03 17:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_faqpagesubtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faqpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Faq - Faq Page',
                'verbose_name_plural': 'Faq - Faq Page',
            },
        ),
    ]
