# Generated by Django 3.2 on 2022-09-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_historypagesubtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historysection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='historysection')),
                ('year', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'History - History Page',
                'verbose_name_plural': 'History - History Page',
            },
        ),
    ]
