# Generated by Django 3.2 on 2022-09-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_teampage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicesection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=200)),
                ('colour', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=1000)),
                ('footer_main_description', models.TextField()),
            ],
            options={
                'verbose_name': 'Service - Homepage',
                'verbose_name_plural': 'Service - Homepage',
            },
        ),
    ]
