# Generated by Django 3.2 on 2022-09-04 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_servicesection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesection',
            old_name='footer_main_description',
            new_name='description',
        ),
    ]
