# Generated by Django 3.2 on 2022-09-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_rename_footer_main_description_servicesection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_page'),
        ),
    ]
