# Generated by Django 3.2 on 2022-09-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_servicepagesubtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serviceskill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('skill_rate', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Service Counter - Service Page',
                'verbose_name_plural': 'Service Counter - Service Page',
            },
        ),
    ]
