# Generated by Django 3.2 on 2022-09-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_serviceskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceskill',
            name='skill_rate',
            field=models.IntegerField(help_text="give number 0 to 100, It's repreasent skill parcentage"),
        ),
    ]
