# Generated by Django 3.2 on 2022-09-06 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresslocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+8801711111000'.", regex='^\\+?1?\\d{11,14}$')])),
                ('email', models.EmailField(max_length=100)),
                ('colour', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Address location - Contactus Page',
                'verbose_name_plural': 'Address location - Contactus Page',
            },
        ),
    ]
