# Generated by Django 3.2 on 2022-09-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_addresslocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactpagesubtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Subtitle - Contact Page',
                'verbose_name_plural': 'Subtitle - Contact Page',
            },
        ),
    ]
