# Generated by Django 3.2 on 2022-09-06 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_contactpagesubtitle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
