# Generated by Django 3.2 on 2022-09-07 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_alter_contact_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
