# Generated by Django 3.2 on 2022-09-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_alter_contact_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricingpagesubtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Subtitle - Pricing Page',
                'verbose_name_plural': 'Subtitle - Pricing Page',
            },
        ),
    ]
