# Generated by Django 3.2 on 2022-09-07 19:19

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_pricingpagesubtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricingcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('sub_title', models.CharField(max_length=500)),
                ('monthly_prices', models.IntegerField()),
                ('yearly_prices', models.IntegerField()),
                ('url', models.URLField(blank=True, null=True)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='mainapp.servicesection')),
            ],
            options={
                'verbose_name': 'Pricing Plan - Pricing Page',
                'verbose_name_plural': 'Pricing Plan - Pricing Page',
            },
        ),
    ]
