# Generated by Django 3.2 on 2022-09-07 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_pricingcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricingattibute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attibute', models.CharField(max_length=500)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_attibute', to='mainapp.pricingcard')),
            ],
            options={
                'verbose_name': 'Pricing Attibute - Pricing Page',
                'verbose_name_plural': 'Pricing Attibute - Pricing Page',
            },
        ),
    ]
