# Generated by Django 3.2 on 2022-09-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_pricingattibute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingcard',
            name='monthly_prices',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricingcard',
            name='yearly_prices',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
