# Generated by Django 3.2 on 2022-09-09 10:14

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_auto_20220908_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingcard',
            name='highlight_colour',
            field=models.CharField(default='#5b84f8', max_length=200),
        ),
        migrations.AlterField(
            model_name='pricingcard',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True),
        ),
    ]
