# Generated by Django 3.2 on 2022-09-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_auto_20220909_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingcard',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
