# Generated by Django 3.2 on 2022-09-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_pricingcard_show_on_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricingsubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('url', models.URLField()),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('package_type', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Pricing Subscribe',
                'verbose_name_plural': 'Pricing Subscribe',
            },
        ),
    ]
