# Generated by Django 3.2 on 2022-09-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_pricingsubscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingsubscribe',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
