# Generated by Django 3.2 on 2022-09-12 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0039_alter_pricingsubscribe_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pricingsubscribe',
        ),
    ]
