# Generated by Django 3.2 on 2022-09-12 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_delete_pricingsubscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricingsubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('url', models.URLField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('package_type', models.CharField(max_length=300)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Pricing Subscribe',
                'verbose_name_plural': 'Pricing Subscribe',
            },
        ),
    ]
