# Generated by Django 3.2 on 2022-09-15 18:00

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0042_privacypolicybody_privacypolicypagesubtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Startupdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(max_length=500)),
                ('body_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Startup Details Page',
                'verbose_name_plural': 'Startup Details Page',
            },
        ),
    ]
