# Generated by Django 3.2 on 2022-09-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0043_startupdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_title', models.CharField(max_length=100)),
                ('achievement_award', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Counter Bar - Homepage',
                'verbose_name_plural': 'Counter Bar - Homepage',
            },
        ),
        migrations.AlterModelOptions(
            name='startupdetails',
            options={'verbose_name': 'Startup Details Page - Homepage Startup', 'verbose_name_plural': 'Startup Details Page - Homepage Startup'},
        ),
    ]
