# Generated by Django 3.2 on 2022-09-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0045_auto_20220917_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seohomepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=200)),
                ('meta_description', models.CharField(max_length=500)),
                ('meta_keywords', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'SEO - Homepage',
                'verbose_name_plural': 'SEO - Homepage',
            },
        ),
        migrations.RemoveField(
            model_name='historysection',
            name='img_alt',
        ),
    ]
