# Generated by Django 3.2 on 2022-09-17 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0046_auto_20220917_2006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seohomepage',
            new_name='Homepagemeta',
        ),
        migrations.AlterModelOptions(
            name='homepagemeta',
            options={'verbose_name': 'Homepage Meta - Homepage', 'verbose_name_plural': 'Homepage Meta - Homepage'},
        ),
    ]
