# Generated by Django 3.2 on 2022-09-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0049_teampagemeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicepagemeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=200)),
                ('meta_description', models.CharField(max_length=500)),
                ('meta_keywords', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Service Meta - Faq Page',
                'verbose_name_plural': 'Service Meta - Faq Page',
            },
        ),
    ]
