# Generated by Django 3.2 on 2022-09-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0051_auto_20220918_0032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homepagemeta',
        ),
        migrations.AlterModelOptions(
            name='headerhomepage',
            options={'verbose_name': 'Header and Meta - Homepage', 'verbose_name_plural': 'Header and Meta - Homepage'},
        ),
        migrations.AddField(
            model_name='headerhomepage',
            name='meta_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='headerhomepage',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='headerhomepage',
            name='site_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
