# Generated by Django 3.2 on 2022-09-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0052_auto_20220925_0020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Startuppagemeta',
        ),
        migrations.AddField(
            model_name='startupsection',
            name='meta_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='startupsection',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='startupsection',
            name='site_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
