# Generated by Django 3.2 on 2022-09-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0053_auto_20220925_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startupsection',
            options={'verbose_name': 'Startup and Meta - Homepage', 'verbose_name_plural': 'Startup and Meta - Homepage'},
        ),
        migrations.RemoveField(
            model_name='startupsection',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='startupsection',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='startupsection',
            name='site_title',
        ),
        migrations.AddField(
            model_name='startupdetails',
            name='meta_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='startupdetails',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='startupdetails',
            name='site_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
