# Generated by Django 3.2 on 2022-09-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0054_auto_20220925_0030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Startupsection',
        ),
        migrations.AlterModelOptions(
            name='startupdetails',
            options={'verbose_name': 'Startup Details Page Meta - Homepage Startup', 'verbose_name_plural': 'Startup Details Page Meta - Homepage Startup'},
        ),
        migrations.AddField(
            model_name='headerhomepage',
            name='startup_section_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headerhomepage',
            name='startup_section_image',
            field=models.ImageField(blank=True, null=True, upload_to='startup_section'),
        ),
        migrations.AddField(
            model_name='headerhomepage',
            name='startup_section_img_alt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='headerhomepage',
            name='startup_section_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
