# Generated by Django 3.2 on 2022-09-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0055_auto_20220925_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faqpagesubtitlemeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_site_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=500, null=True)),
                ('sub_title', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Subtitle and Meta - Faq Page',
                'verbose_name_plural': 'Subtitle and Meta - Faq Page',
            },
        ),
        migrations.DeleteModel(
            name='Faqpagemeta',
        ),
        migrations.DeleteModel(
            name='Faqpagesubtitle',
        ),
    ]
