# Generated by Django 3.2 on 2022-09-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0056_auto_20220925_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicepagesubtitlemeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_site_title', models.CharField(max_length=200)),
                ('meta_description', models.CharField(max_length=500)),
                ('meta_keywords', models.CharField(max_length=500)),
                ('sub_title', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Service Subtitle and Meta - Service Page',
                'verbose_name_plural': 'Service Subtitle and Meta - Service Page',
            },
        ),
        migrations.DeleteModel(
            name='Servicepagemeta',
        ),
        migrations.DeleteModel(
            name='Servicepagesubtitle',
        ),
        migrations.AlterModelOptions(
            name='faqpagesubtitlemeta',
            options={'verbose_name': 'Faq Subtitle and Meta - Faq Page', 'verbose_name_plural': 'Faq Subtitle and Meta - Faq Page'},
        ),
    ]
